<?php

declare(strict_types=1);

namespace Pharaonic\SmartEnum\Tests;

use Pharaonic\SmartEnum\CaseMethods;
use Pharaonic\SmartEnum\Tools\EnumDocBlockGenerator;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Verifies the docblocks generated for is<Case>() checks.
 */
final class EnumDocBlockGeneratorTest extends TestCase
{
    private EnumDocBlockGenerator $generator;

    protected function setUp(): void
    {
        $this->generator = EnumDocBlockGenerator::create();
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function caseNameProvider(): iterable
    {
        yield 'Active' => ['Active'];
        yield 'PENDING' => ['PENDING'];
        yield 'IN_COOKING' => ['IN_COOKING'];
        yield 'InProgress' => ['InProgress'];
        yield 'onHold' => ['onHold'];
        yield 'HTTPError' => ['HTTPError'];
        yield 'Level2' => ['Level2'];
    }

    #[DataProvider('caseNameProvider')]
    public function testGeneratedMethodMatchesCaseMethods(string $case): void
    {
        $result = $this->generator->process(self::enumUsingSmartEnum($case));

        $this->assertNull($result['error']);
        $this->assertTrue($result['changed']);
        $this->assertSame(1, $result['enums']);
        $this->assertStringContainsString(
            '@method bool ' . CaseMethods::methodName($case) . '()',
            $result['contents'],
        );
    }

    public function testInsertsDocBlockWhenMissing(): void
    {
        $result = $this->generator->process(self::enumUsingSmartEnum('Active'));

        $this->assertSame(<<<'PHP'
<?php

/**
 * <auto-generated enum methods>
 * @method bool isActive()
 * </auto-generated enum methods>
 */
enum Status
{
    use SmartEnum;

    case Active;
}

PHP, $result['contents']);
    }

    public function testAppendsSectionToExistingDocBlock(): void
    {
        $result = $this->generator->process(<<<'PHP'
<?php

/**
 * Order status.
 *
 * @package App
 */
enum Status
{
    use SmartEnum;

    case Active;
}

PHP);

        $this->assertTrue($result['changed']);
        $this->assertSame(<<<'PHP'
<?php

/**
 * Order status.
 *
 * @package App
 * <auto-generated enum methods>
 * @method bool isActive()
 * </auto-generated enum methods>
 */
enum Status
{
    use SmartEnum;

    case Active;
}

PHP, $result['contents']);
    }

    public function testReplacesExistingGeneratedSection(): void
    {
        $result = $this->generator->process(<<<'PHP'
<?php

/**
 * Order status.
 *
 * <auto-generated enum methods>
 * @method bool isPending()
 * </auto-generated enum methods>
 */
enum Status
{
    use SmartEnum;

    case Active;
}

PHP);

        $this->assertTrue($result['changed']);
        $this->assertSame(<<<'PHP'
<?php

/**
 * Order status.
 *
 * <auto-generated enum methods>
 * @method bool isActive()
 * </auto-generated enum methods>
 */
enum Status
{
    use SmartEnum;

    case Active;
}

PHP, $result['contents']);
    }

    public function testSecondRunMakesNoChange(): void
    {
        $once = $this->generator->process(self::enumUsingSmartEnum('Active'));
        $twice = $this->generator->process($once['contents']);

        $this->assertFalse($twice['changed']);
        $this->assertSame(1, $twice['enums']);
        $this->assertNull($twice['error']);
        $this->assertSame($once['contents'], $twice['contents']);
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function smartEnumTraitProvider(): iterable
    {
        yield 'short name' => ['SmartEnum'];
        yield 'fully qualified' => ['\\Pharaonic\\SmartEnum\\SmartEnum'];
    }

    #[DataProvider('smartEnumTraitProvider')]
    public function testUpdatesEnumsThatUseSmartEnum(string $trait): void
    {
        $result = $this->generator->process(self::enumUsingSmartEnum('Active', $trait));

        $this->assertNull($result['error']);
        $this->assertTrue($result['changed']);
        $this->assertSame(1, $result['enums']);
        $this->assertStringContainsString('@method bool isActive()', $result['contents']);
    }

    public function testIgnoresEnumWithoutSmartEnum(): void
    {
        $source = <<<'PHP'
<?php

enum Status
{
    use NotSmartEnum;

    case Active;
}

PHP;

        $result = $this->generator->process($source);

        $this->assertNull($result['error']);
        $this->assertFalse($result['changed']);
        $this->assertSame(0, $result['enums']);
        $this->assertSame($source, $result['contents']);
    }

    public function testUpdatesOnlyTheEnumThatUsesSmartEnum(): void
    {
        $result = $this->generator->process(<<<'PHP'
<?php

enum Plain
{
    case Active;
}

enum Status
{
    use SmartEnum;

    case Pending;
}

PHP);

        $this->assertSame(1, $result['enums']);
        $this->assertSame(<<<'PHP'
<?php

enum Plain
{
    case Active;
}

/**
 * <auto-generated enum methods>
 * @method bool isPending()
 * </auto-generated enum methods>
 */
enum Status
{
    use SmartEnum;

    case Pending;
}

PHP, $result['contents']);
    }

    public function testAmbiguousCasesShareOneMethodTag(): void
    {
        $result = $this->generator->process(<<<'PHP'
<?php

enum Task
{
    use SmartEnum;

    case IN_PROGRESS;
    case InProgress;
    case Done;
}

PHP);

        $this->assertSame(1, substr_count($result['contents'], '@method bool isInProgress()'));
        $this->assertStringContainsString('@method bool isDone()', $result['contents']);
        $this->assertSame(<<<'PHP'
<?php

/**
 * <auto-generated enum methods>
 * @method bool isInProgress()
 * @method bool isDone()
 * </auto-generated enum methods>
 */
enum Task
{
    use SmartEnum;

    case IN_PROGRESS;
    case InProgress;
    case Done;
}

PHP, $result['contents']);
    }

    public function testInvalidPhpReturnsErrorAndKeepsContents(): void
    {
        $source = "<?php\nthis is not valid;\n";

        $result = $this->generator->process($source);

        $this->assertFalse($result['changed']);
        $this->assertSame(0, $result['enums']);
        $this->assertSame($source, $result['contents']);
        $this->assertNotNull($result['error']);
    }

    public function testDryRunDoesNotWrite(): void
    {
        $source = self::enumUsingSmartEnum('Active');
        $directory = $this->tempDirectory();
        $file = $directory . '/Status.php';
        file_put_contents($file, $source);

        try {
            $output = $this->runCli($directory, ['--dry-run']);

            $this->assertStringContainsString('[DRY-RUN]', $output);
            $this->assertStringContainsString('Files needing updates: 1', $output);
            $this->assertStringContainsString('Errors: 0', $output);
            $this->assertSame($source, file_get_contents($file));
        } finally {
            $this->deleteDirectory($directory);
        }
    }

    public function testCliWritesDocBlock(): void
    {
        $directory = $this->tempDirectory();
        $file = $directory . '/Status.php';
        file_put_contents($file, self::enumUsingSmartEnum('Active'));

        try {
            $output = $this->runCli($directory, []);

            $this->assertStringContainsString('[UPDATE]', $output);
            $this->assertStringContainsString('Enums scanned: 1', $output);
            $this->assertStringContainsString('Files needing updates: 1', $output);
            $this->assertStringContainsString('Errors: 0', $output);

            $contents = file_get_contents($file);
            $this->assertIsString($contents);
            $this->assertStringContainsString('@method bool isActive()', $contents);
        } finally {
            $this->deleteDirectory($directory);
        }
    }

    private static function enumUsingSmartEnum(string $case, string $trait = 'SmartEnum'): string
    {
        return <<<PHP
<?php

enum Status
{
    use {$trait};

    case {$case};
}

PHP;
    }

    private function tempDirectory(): string
    {
        $directory = sys_get_temp_dir() . '/php-smart-enum-docblocks-' . uniqid('', true);
        mkdir($directory);

        return $directory;
    }

    /**
     * @param list<string> $arguments
     */
    private function runCli(string $directory, array $arguments): string
    {
        $command = array_merge(
            [PHP_BINARY, dirname(__DIR__) . '/bin/generate-enum-docblocks.php'],
            $arguments,
            [$directory],
        );

        $pipes = [];
        $process = proc_open($command, [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);

        if ($process === false) {
            $this->fail('Could not start the generator.');
        }

        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);

        $exitCode = proc_close($process);

        $this->assertIsString($stdout);
        $this->assertIsString($stderr);
        $this->assertSame(0, $exitCode, $stderr);

        return $stdout;
    }

    private function deleteDirectory(string $directory): void
    {
        $file = $directory . '/Status.php';

        if (is_file($file)) {
            unlink($file);
        }

        if (is_dir($directory)) {
            rmdir($directory);
        }
    }
}
